# macOS package list (Apple Silicon). This is the macOS source of record per
# docs/package-matrix.md; the Ubuntu equivalents live in script/packages/ubuntu.sh
# and the topic installers. Consumed only on macOS via homebrew/install.sh.

tap "homebrew/bundle"
tap "homebrew/services"

# Text editors
brew "ctags-exuberant"
brew "markdown"
brew "vim"

# Terminal Tools
brew "ack"
brew "amazon-ecs-cli"
brew "awscli"
brew "coreutils"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "gpg"
brew "gron"
brew "hub"
brew "jq"
brew "nmap"
brew "proctools"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "shellcheck"
brew "the_silver_searcher"
brew "tmux"
brew "wget"
brew "yq"
cask "aws-vault"

# Application Dependencies
brew "autoconf"
brew "automake"
brew "awslogs"
brew "binutils"
brew "bison"
brew "chruby"
brew "gcc"
brew "gdbm" 
brew "imagemagick"
brew "libffi"
brew "libksba"
brew "libyaml"
brew "make"
brew "memcached"
brew "openssl@1.1"
brew "openssl@3"
brew "readline"
brew "redis"
brew "ruby-install"

# Hashicorp Tools
brew "consul"
brew "nomad"
brew "vault"
brew "tfenv"

# Databases
brew "mysql@5.7"
brew "postgresql"

# Javascript
brew "nvm"
brew "yarn"

# git
brew "git-lfs"

# Platform Tools
brew "direnv"